name: bluebuild
on:
  schedule:
    - cron:
        "00 06,12,18,00 * * *" # build at 00:00, 06:00, 12:00, and 18:00 UTC every day
  push:
    paths-ignore: # don't rebuild if only documentation has changed
      - "**.md"
      - ".github/workflows/build.yml"

  workflow_dispatch: # allow manually triggering builds
concurrency:
  # only run one build at a time
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
jobs:
  bluebuild:
    name: Build Custom Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false # stop GH from cancelling all matrix builds if one fails
      matrix:
        recipe:
          - stable.yml
          - stable-daily.yml
          - nvidia-open-stable.yml
          - nvidia-open-stable-daily.yml
          - nvidia-stable.yml
          - nvidia-stable-daily.yml
    steps:
      - name: Checkout Repository
        if: github.event_name == 'schedule'
        uses: actions/checkout@v5

      - name: Install Dependencies
        if: github.event_name == 'schedule'
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

          # Install yq
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

          # Install skopeo
          sudo apt-get install -y skopeo

      - name: Check if build is needed
        if: github.event_name == 'schedule'
        id: should_build
        run: |
          if scripts/should-build.sh ${{ matrix.recipe }}; then
            echo "build_needed=0" >> $GITHUB_OUTPUT
          else
            echo "build_needed=1" >> $GITHUB_OUTPUT
          fi

      # the build is fully handled by the reusable github action
      - name: Build Custom Image
        if: github.event_name != 'schedule' || steps.should_build.outputs.build_needed != '0'
        uses: blue-build/github-action@v1.9
        with:
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}

          # enabled by default, disable if your image is small and you want faster builds
          maximize_build_space: false
